SELECT * FROM `persona`WHERE nombre='Victor';
SELECT nombre `persona`, apellido FROM persona WHERE nombre ='Victor';
SELECT * FROM `persona` WHERE nombre= 'Victor' OR apellido = 'Rojas';
SELECT * FROM `persona` WHERE nombre= 'Gaby' OR apellido = 'Rodriguez';
SELECT * FROM `persona` WHERE nombre= 'Gustavo' AND apellido = 'Rodriguez';
SELECT * FROM `persona` WHERE nombre LIKE '%a';
SELECT * FROM `persona` WHERE nombre LIKE 'a%';
SELECT * FROM `persona` WHERE nombre LIKE '%a%';
SELECT * FROM `persona` WHERE (nombre LIKE'%a%' OR apellido LIKE '%o%') AND id>=4;
SELECT COUNT(*) FROM `persona`;
SELECT COUNT(*) as cantidaf FROM `persona`;
